export const PILOT_QUERIES = [
  'calc(100%',
  'calc(var(',
  'calc(100vh',
  'calc(min(',
  'calc(clamp(',
];
export const FULL_QUERIES = [
  'calc(100%',
  'calc(50%',
  'calc(100vh',
  'calc(100vw',
  'calc(1px',
  'calc(2px',
  'calc(1em',
  'calc(1rem',
  'calc(0.5rem',
  'calc(1.5rem',
  'calc(1deg',
  'calc(1turn',
  'calc(1s',
  'calc(1fr',
  'calc(1ch',
  'calc(var(',
  'calc( var(',
  'calc(100% -',
  'calc(100% +',
  'calc(100% /',
  'calc(100% *',
  'calc(min(',
  'calc(max(',
  'calc(clamp(',
  'calc(round(',
  'calc(mod(',
  'calc(abs(',
  'calc(sin(',
  'calc(cos(',
  'calc(pow(',
  'calc(sqrt(',
  'calc(hypot(',
  'margin: calc(',
  'padding: calc(',
  'width: calc(',
  'height: calc(',
  'top: calc(',
  'left: calc(',
  'transform: translate(calc(',
  'grid-template-columns: calc(',
  'calc((',
  'calc(((',
  'calc( (',
  'calc( ((',
  'calc(calc(',
  'calc( calc(',
  'calc(0',
  'calc(1',
  'calc(2',
  'calc(3',
  'calc(4',
  'calc(5',
  'calc(6',
  'calc(7',
  'calc(8',
  'calc(9',
  'calc(.5',
  'calc(.25',
  'calc(-.',
  'calc(-1',
  'calc(-2',
  'calc(env(',
  'calc(attr(',
];
export const LANGUAGES = ['css', 'scss', 'less'];
